[package]
name = "paisleys_paradox"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "*"
ncollide2d = "*"
serde = { version = "*", features = ["derive"] }
rapier2d = "*"

[[bin]]
name = "random"

[profile.dev.package.rapier2d]
opt-level = 3

